// Mock data for development — replace with real API/DB calls in production

import type { User, Campaign, Task, ContentItem, Approval, ActivityItem, AnalyticsSnapshot } from "@/types";

// ─── Real album cover art (Spotify CDN) ──────────────────────────────────────
export const COVERS = {
  ecclesiastes: "https://i.scdn.co/image/ab67616d0000b2739e50f88489ef308f66f9613e",
  mrsKey:        "https://i.scdn.co/image/ab67616d0000b273efe470094cb9bb5b6921adca",
  repent:        "https://i.scdn.co/image/ab67616d0000b273caf8aa59011bfa50cc75e2cc",
  discernment:   "https://i.scdn.co/image/ab67616d0000b2734b3d604ccd4a14a9f737a8f7",
  tkeyVsTony:    "https://i.scdn.co/image/ab67616d0000b2732d0f05a694d595f5624551fd",
};

export const ARTIST_PHOTO = "https://i.scdn.co/image/ab6761610000e5ebac24eee9ce79217efc023fba";

// Current session user — swap index to simulate different roles (0 = Artist, 1 = CD)
// Replace with real auth session in production
export const CURRENT_USER_INDEX = 1; // Tatiyana, Creative Ops Director

export const MOCK_USERS: User[] = [
  {
    id: "u1",
    name: "Lil Tony Official",
    displayName: "Key",
    email: "key@liltonystudio.io",
    image: ARTIST_PHOTO,
    role: "ARTIST_CEO",
    status: "ACTIVE",
    timezone: "America/Chicago",
  },
  {
    id: "u2",
    name: "Tatiyana",
    email: "whoistati@thesighteproject.com",
    image: "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=96&h=96&fit=crop",
    role: "CREATIVE_OPS_DIRECTOR",
    status: "ACTIVE",
    timezone: "America/Chicago",
  },
  {
    id: "u3",
    name: "Darius King",
    email: "darius@liltonystudio.io",
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=96&h=96&fit=crop",
    role: "EDITOR",
    status: "BUSY",
    timezone: "America/Chicago",
  },
  {
    id: "u4",
    name: "Sofia Reyes",
    email: "sofia@liltonystudio.io",
    image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=96&h=96&fit=crop",
    role: "SOCIAL_MEDIA",
    status: "ACTIVE",
    timezone: "America/New_York",
  },
  {
    id: "u5",
    name: "Kaito Mori",
    email: "kaito@liltonystudio.io",
    role: "PHOTOGRAPHER_VIDEOGRAPHER",
    status: "AWAY",
    timezone: "America/Los_Angeles",
  },
  {
    id: "u6",
    name: "Amara Osei",
    email: "amara@liltonystudio.io",
    image: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=96&h=96&fit=crop",
    role: "GRAPHIC_DESIGNER",
    status: "ACTIVE",
    timezone: "America/Chicago",
  },
];

export const CURRENT_USER = MOCK_USERS[CURRENT_USER_INDEX];

export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    id: "c1",
    name: "Mrs.Key — Album Rollout",
    description: "Full rollout campaign for Mrs.Key — 13 tracks, visual world, press & DSP push",
    status: "ACTIVE",
    phase: "ANALYTICS",
    startDate: "2026-03-01",
    endDate: "2026-05-31",
    platforms: ["instagram", "tiktok", "spotify", "youtube"],
    coverImage: COVERS.mrsKey,
    progress: 84,
    taskCount: 28,
    completedTasks: 24,
    teamMembers: [MOCK_USERS[0], MOCK_USERS[1], MOCK_USERS[2], MOCK_USERS[3]],
  },
  {
    id: "c2",
    name: "Ecclesiastes — Single Push",
    description: "Rollout for the Ecclesiastes single — faith-driven narrative content strategy",
    status: "ACTIVE",
    phase: "POSTED",
    startDate: "2026-04-15",
    endDate: "2026-05-30",
    platforms: ["instagram", "tiktok", "spotify", "youtube"],
    coverImage: COVERS.ecclesiastes,
    progress: 91,
    taskCount: 14,
    completedTasks: 13,
    teamMembers: [MOCK_USERS[0], MOCK_USERS[3], MOCK_USERS[5]],
  },
  {
    id: "c3",
    name: "Press Push — HipHopDX / AllHipHop",
    description: "Feature placement coordination, press kit delivery, and bio refresh",
    status: "PLANNING",
    phase: "PLANNING",
    startDate: "2026-05-20",
    endDate: "2026-06-15",
    platforms: ["press", "website"],
    progress: 18,
    taskCount: 10,
    completedTasks: 2,
    teamMembers: [MOCK_USERS[1], MOCK_USERS[2]],
  },
  {
    id: "c4",
    name: "REPENT! — Catalog Push",
    description: "Re-ignite momentum on REPENT! — playlist pitching, editorial, and content wave",
    status: "PLANNING",
    phase: "IDEA",
    startDate: "2026-06-01",
    endDate: "2026-07-15",
    platforms: ["instagram", "tiktok", "spotify", "youtube", "twitter"],
    coverImage: COVERS.repent,
    progress: 10,
    taskCount: 18,
    completedTasks: 2,
    teamMembers: [MOCK_USERS[0], MOCK_USERS[1], MOCK_USERS[3], MOCK_USERS[5]],
  },
];

export const MOCK_TASKS: Task[] = [
  {
    id: "t1",
    title: 'Edit "3 AM" visualizer (YouTube cut)',
    status: "IN_PROGRESS",
    priority: "HIGH",
    assignee: MOCK_USERS[2],
    dueDate: "2026-05-22",
    campaignName: "Mrs.Key — Album Rollout",
    type: "DELIVERABLE",
  },
  {
    id: "t2",
    title: "Design Mrs.Key merch mockups (3 formats)",
    status: "IN_REVIEW",
    priority: "HIGH",
    assignee: MOCK_USERS[5],
    dueDate: "2026-05-20",
    campaignName: "Mrs.Key — Album Rollout",
    type: "DELIVERABLE",
  },
  {
    id: "t3",
    title: "Schedule Ecclesiastes Week 3 content (May 22–28)",
    status: "TODO",
    priority: "MEDIUM",
    assignee: MOCK_USERS[3],
    dueDate: "2026-05-21",
    campaignName: "Ecclesiastes — Single Push",
    type: "DELIVERABLE",
  },
  {
    id: "t4",
    title: "Send hi-res artist photos to HipHopDX",
    status: "TODO",
    priority: "URGENT",
    assignee: MOCK_USERS[4],
    dueDate: "2026-05-19",
    campaignName: "Press Push — HipHopDX / AllHipHop",
    type: "DELIVERABLE",
  },
  {
    id: "t5",
    title: "Update press kit bio (post Mrs.Key release)",
    status: "DONE",
    priority: "MEDIUM",
    assignee: MOCK_USERS[1],
    dueDate: "2026-05-15",
    campaignName: "Press Push — HipHopDX / AllHipHop",
    type: "DELIVERABLE",
  },
  {
    id: "t6",
    title: "Review + approve social copy — REPENT! teaser week",
    status: "IN_REVIEW",
    priority: "MEDIUM",
    assignee: MOCK_USERS[0],
    dueDate: "2026-05-20",
    campaignName: "REPENT! — Catalog Push",
    type: "APPROVAL",
  },
];

export const MOCK_CONTENT: ContentItem[] = [
  {
    id: "ci1",
    title: '"3 AM" — Snippet reel (hook section)',
    type: "REEL",
    phase: "EDITING",
    platforms: ["instagram", "tiktok"],
    scheduledAt: "2026-05-25T14:00:00Z",
    assignee: MOCK_USERS[2],
    campaignName: "Mrs.Key — Album Rollout",
  },
  {
    id: "ci2",
    title: "Behind the scenes — Mrs.Key recording sessions",
    type: "STORY",
    phase: "APPROVED",
    platforms: ["instagram"],
    scheduledAt: "2026-05-21T18:00:00Z",
    assignee: MOCK_USERS[3],
    campaignName: "Mrs.Key — Album Rollout",
  },
  {
    id: "ci3",
    title: "Ecclesiastes — Testimony post (caption story)",
    type: "CAROUSEL",
    phase: "REVIEW",
    platforms: ["instagram"],
    scheduledAt: "2026-05-22T12:00:00Z",
    assignee: MOCK_USERS[5],
    campaignName: "Ecclesiastes — Single Push",
  },
  {
    id: "ci4",
    title: 'REPENT! — "Why I made this album" announcement',
    type: "PHOTO",
    phase: "PLANNING",
    platforms: ["instagram", "twitter"],
    scheduledAt: "2026-06-10T09:00:00Z",
    assignee: MOCK_USERS[3],
    campaignName: "REPENT! — Catalog Push",
  },
  {
    id: "ci5",
    title: '"2 Sides To Every Story" — YouTube visualizer',
    type: "VIDEO",
    phase: "PRODUCTION",
    platforms: ["youtube"],
    scheduledAt: "2026-06-15T16:00:00Z",
    assignee: MOCK_USERS[2],
    campaignName: "Mrs.Key — Album Rollout",
  },
  {
    id: "ci6",
    title: '"Who\'s The Flyest" freestyle clip (organic)',
    type: "VIDEO",
    phase: "POSTED",
    platforms: ["tiktok"],
    assignee: MOCK_USERS[3],
  },
];

export const MOCK_APPROVALS: Approval[] = [
  {
    id: "a1",
    title: "Mrs.Key merch mockups — Final variant",
    type: "task",
    status: "PENDING",
    requester: MOCK_USERS[5],
    requestedAt: "2026-05-18T10:30:00Z",
    priority: "HIGH",
  },
  {
    id: "a2",
    title: "REPENT! catalog push — Social copy",
    type: "content",
    status: "PENDING",
    requester: MOCK_USERS[3],
    requestedAt: "2026-05-18T08:15:00Z",
    priority: "MEDIUM",
  },
  {
    id: "a3",
    title: "Press kit bio — Post Mrs.Key update",
    type: "task",
    status: "REVISION_REQUESTED",
    requester: MOCK_USERS[1],
    requestedAt: "2026-05-17T16:00:00Z",
    priority: "MEDIUM",
  },
];

export const MOCK_ACTIVITY: ActivityItem[] = [
  {
    id: "ac1",
    user: MOCK_USERS[2],
    action: "uploaded",
    entityType: "asset",
    entityName: "3AM_visualizer_v2_final.mp4",
    timestamp: "2026-05-18T11:45:00Z",
  },
  {
    id: "ac2",
    user: MOCK_USERS[5],
    action: "submitted for approval",
    entityType: "task",
    entityName: "Mrs.Key merch mockups — Final variant",
    timestamp: "2026-05-18T10:30:00Z",
  },
  {
    id: "ac3",
    user: MOCK_USERS[3],
    action: "scheduled",
    entityType: "content",
    entityName: "Behind the scenes — Mrs.Key recording sessions",
    timestamp: "2026-05-18T09:20:00Z",
  },
  {
    id: "ac4",
    user: MOCK_USERS[1],
    action: "created campaign",
    entityType: "campaign",
    entityName: "REPENT! — Catalog Push",
    timestamp: "2026-05-18T08:00:00Z",
  },
  {
    id: "ac5",
    user: MOCK_USERS[4],
    action: "completed",
    entityType: "task",
    entityName: "Artist photo shoot — Press set B",
    timestamp: "2026-05-17T18:30:00Z",
  },
  {
    id: "ac6",
    user: MOCK_USERS[0],
    action: "approved",
    entityType: "task",
    entityName: "Ecclesiastes social copy — Week 2",
    timestamp: "2026-05-17T15:00:00Z",
  },
];

// ─── Analytics — real Spotify scale (1.27M monthly listeners, 342K followers) ──

export const MOCK_ANALYTICS: AnalyticsSnapshot[] = [
  {
    platform: "instagram",
    followers: 89400,
    followersGrowth: 3.1,
    impressions: 620000,
    engagement: 31200,
    engagementRate: 5.0,
    shares: 8600,
    saves: 6100,
  },
  {
    platform: "tiktok",
    followers: 214000,
    followersGrowth: 7.4,
    impressions: 2100000,
    engagement: 118000,
    engagementRate: 5.6,
    shares: 44000,
    saves: 19000,
  },
  {
    platform: "youtube",
    followers: 41000,
    followersGrowth: 2.2,
    impressions: 310000,
    engagement: 18600,
    engagementRate: 6.0,
    shares: 3800,
    saves: 5200,
  },
  {
    platform: "spotify",
    // 342,354 followers, 1,273,747 monthly listeners
    followers: 342354,
    followersGrowth: 4.6,
    impressions: 1273747,
    engagement: 342354,
    engagementRate: 26.9, // saves/follows as % of listeners
    shares: 28000,
    saves: 94000,
  },
];

export const MONTHLY_ENGAGEMENT_DATA = [
  { month: "Dec", instagram: 19000, tiktok: 64000,  youtube: 10000 },
  { month: "Jan", instagram: 22000, tiktok: 78000,  youtube: 11500 },
  { month: "Feb", instagram: 24000, tiktok: 91000,  youtube: 13000 },
  { month: "Mar", instagram: 27000, tiktok: 104000, youtube: 15000 },
  { month: "Apr", instagram: 29000, tiktok: 112000, youtube: 17200 },
  { month: "May", instagram: 31200, tiktok: 118000, youtube: 18600 },
];
