// Mock data for development — replace with real API/DB calls in production

import type { User, Campaign, Task, ContentItem, Approval, ActivityItem, AnalyticsSnapshot } from "@/types";

// ─── Real album cover art (Spotify CDN) ──────────────────────────────────────
export const COVERS = {
  ecclesiastes: "https://i.scdn.co/image/ab67616d0000b2739e50f88489ef308f66f9613e",
  mrsKey:        "https://i.scdn.co/image/ab67616d0000b273efe470094cb9bb5b6921adca",
  repent:        "https://i.scdn.co/image/ab67616d0000b273caf8aa59011bfa50cc75e2cc",
  discernment:   "https://i.scdn.co/image/ab67616d0000b2734b3d604ccd4a14a9f737a8f7",
  tkeyVsTony:    "https://i.scdn.co/image/ab67616d0000b2732d0f05a694d595f5624551fd",
};

export const ARTIST_PHOTO = "https://i.scdn.co/image/ab6761610000e5ebac24eee9ce79217efc023fba";

// Current session user — swap index to simulate different roles (0 = Artist, 1 = CD)
// Replace with real auth session in production
export const CURRENT_USER_INDEX = 1; // Tatiyana, Creative Ops Director

export const MOCK_USERS: User[] = [
  {
    id: "u1",
    name: "Lil Tony Official",
    displayName: "Key",
    email: "key@liltonystudio.io",
    image: ARTIST_PHOTO,
    role: "ARTIST_CEO",
    status: "ACTIVE",
    timezone: "America/Chicago",
  },
  {
    id: "u2",
    name: "Tatiyana",
    displayName: "Tati",
    email: "whoistati@thesighteproject.com",
    image: "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=96&h=96&fit=crop",
    role: "CREATIVE_OPS_DIRECTOR",
    status: "ACTIVE",
    timezone: "America/Chicago",
  },
  {
    id: "u3",
    name: "Darius King",
    displayName: "Darius",
    email: "darius@liltonystudio.io",
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=96&h=96&fit=crop",
    role: "EDITOR",
    status: "BUSY",
    timezone: "America/Chicago",
  },
  {
    id: "u4",
    name: "Sofia Reyes",
    displayName: "Sofia",
    email: "sofia@liltonystudio.io",
    image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=96&h=96&fit=crop",
    role: "SOCIAL_MEDIA",
    status: "ACTIVE",
    timezone: "America/New_York",
  },
  {
    id: "u5",
    name: "Kaito Mori",
    displayName: "Kaito",
    email: "kaito@liltonystudio.io",
    role: "PHOTOGRAPHER_VIDEOGRAPHER",
    status: "AWAY",
    timezone: "America/Los_Angeles",
  },
  {
    id: "u6",
    name: "Amara Osei",
    displayName: "Amara",
    email: "amara@liltonystudio.io",
    image: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=96&h=96&fit=crop",
    role: "GRAPHIC_DESIGNER",
    status: "ACTIVE",
    timezone: "America/Chicago",
  },
];

export const CURRENT_USER = MOCK_USERS[CURRENT_USER_INDEX];

export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    id: "c1",
    name: "Elijah — Album Rollout",
    description: "Full rollout campaign for Elijah — 12 tracks, cinematic visual world, DSP push, July 18 drop",
    status: "ACTIVE",
    phase: "PRODUCTION",
    startDate: "2026-05-01",
    endDate: "2026-07-25",
    platforms: ["instagram", "tiktok", "spotify", "youtube", "twitter"],
    progress: 45,
    taskCount: 32,
    completedTasks: 14,
    teamMembers: [MOCK_USERS[0], MOCK_USERS[1], MOCK_USERS[2], MOCK_USERS[3], MOCK_USERS[4], MOCK_USERS[5]],
  },
  {
    id: "c2",
    name: "Gravity — Single Push",
    description: 'Lead single campaign — YouTube premiere June 3, vertical edit, DSP push, and press rollout',
    status: "ACTIVE",
    phase: "REVIEW",
    startDate: "2026-05-20",
    endDate: "2026-06-15",
    platforms: ["instagram", "tiktok", "youtube", "twitter"],
    progress: 62,
    taskCount: 12,
    completedTasks: 8,
    teamMembers: [MOCK_USERS[0], MOCK_USERS[1], MOCK_USERS[2], MOCK_USERS[3]],
  },
  {
    id: "c3",
    name: "Mrs.Key — Album Rollout",
    description: "Full rollout campaign for Mrs.Key — 13 tracks, visual world, press & DSP push",
    status: "ACTIVE",
    phase: "ANALYTICS",
    startDate: "2026-03-01",
    endDate: "2026-05-31",
    platforms: ["instagram", "tiktok", "spotify", "youtube"],
    coverImage: COVERS.mrsKey,
    progress: 84,
    taskCount: 28,
    completedTasks: 24,
    teamMembers: [MOCK_USERS[0], MOCK_USERS[1], MOCK_USERS[2], MOCK_USERS[3]],
  },
  {
    id: "c4",
    name: "REPENT! — Catalog Push",
    description: "Re-ignite momentum on REPENT! — playlist pitching, editorial, and content wave",
    status: "PLANNING",
    phase: "IDEA",
    startDate: "2026-06-01",
    endDate: "2026-07-15",
    platforms: ["instagram", "tiktok", "spotify", "youtube", "twitter"],
    coverImage: COVERS.repent,
    progress: 10,
    taskCount: 18,
    completedTasks: 2,
    teamMembers: [MOCK_USERS[0], MOCK_USERS[1], MOCK_USERS[3], MOCK_USERS[5]],
  },
];

export const MOCK_TASKS: Task[] = [
  {
    id: "t1",
    title: 'Set up YouTube premiere — "Gravity" MV (June 3)',
    status: "TODO",
    priority: "URGENT",
    assignee: MOCK_USERS[1],
    dueDate: "2026-05-30",
    campaignName: "Gravity — Single Push",
    type: "DELIVERABLE",
  },
  {
    id: "t2",
    title: 'Approve "Gravity" MV final cut',
    status: "IN_REVIEW",
    priority: "HIGH",
    assignee: MOCK_USERS[0],
    dueDate: "2026-05-30",
    campaignName: "Gravity — Single Push",
    type: "APPROVAL",
  },
  {
    id: "t3",
    title: '"Gravity" vertical edit — final color grade + captions',
    status: "IN_PROGRESS",
    priority: "HIGH",
    assignee: MOCK_USERS[2],
    dueDate: "2026-06-01",
    campaignName: "Gravity — Single Push",
    type: "DELIVERABLE",
  },
  {
    id: "t4",
    title: "Pre-save campaign social kit — all platforms",
    status: "TODO",
    priority: "HIGH",
    assignee: MOCK_USERS[3],
    dueDate: "2026-06-01",
    campaignName: "Elijah — Album Rollout",
    type: "DELIVERABLE",
  },
  {
    id: "t5",
    title: "Apple Music editorial pitch — Elijah",
    status: "DONE",
    priority: "HIGH",
    assignee: MOCK_USERS[1],
    dueDate: "2026-05-29",
    campaignName: "Elijah — Album Rollout",
    type: "DELIVERABLE",
  },
  {
    id: "t6",
    title: 'YouTube description, credits + timestamps — "Gravity" MV',
    status: "IN_PROGRESS",
    priority: "MEDIUM",
    assignee: MOCK_USERS[3],
    dueDate: "2026-06-02",
    campaignName: "Gravity — Single Push",
    type: "DELIVERABLE",
  },
];

export const MOCK_CONTENT: ContentItem[] = [
  {
    id: "ci1",
    title: '"Gravity" — Official music video',
    type: "VIDEO",
    phase: "REVIEW",
    platforms: ["youtube", "instagram"],
    scheduledAt: "2026-06-03T00:00:00Z",
    assignee: MOCK_USERS[2],
    campaignName: "Gravity — Single Push",
  },
  {
    id: "ci2",
    title: '"Gravity" — Vertical edit (60s)',
    type: "REEL",
    phase: "EDITING",
    platforms: ["instagram", "tiktok"],
    scheduledAt: "2026-06-03T00:00:00Z",
    assignee: MOCK_USERS[2],
    campaignName: "Gravity — Single Push",
  },
  {
    id: "ci3",
    title: '"Gravity" — Single announcement graphic',
    type: "PHOTO",
    phase: "APPROVED",
    platforms: ["instagram", "tiktok", "twitter"],
    scheduledAt: "2026-05-28T09:00:00Z",
    assignee: MOCK_USERS[5],
    campaignName: "Gravity — Single Push",
  },
  {
    id: "ci4",
    title: "Pre-save campaign launch — link + visual",
    type: "PHOTO",
    phase: "EDITING",
    platforms: ["instagram", "tiktok", "twitter"],
    scheduledAt: "2026-06-10T09:00:00Z",
    assignee: MOCK_USERS[3],
    campaignName: "Elijah — Album Rollout",
  },
  {
    id: "ci5",
    title: 'Studio BTS — "Gravity" MV shoot day',
    type: "REEL",
    phase: "PRODUCTION",
    platforms: ["instagram", "tiktok"],
    scheduledAt: "2026-06-10T12:00:00Z",
    assignee: MOCK_USERS[4],
    campaignName: "Elijah — Album Rollout",
  },
  {
    id: "ci6",
    title: '"Smoke & Mirrors" — 30s snippet',
    type: "REEL",
    phase: "SCHEDULED",
    platforms: ["tiktok", "instagram"],
    scheduledAt: "2026-06-20T14:00:00Z",
    assignee: MOCK_USERS[2],
    campaignName: "Elijah — Album Rollout",
  },
];

export const MOCK_APPROVALS: Approval[] = [
  {
    id: "a1",
    title: '"Gravity" MV final cut — management sign-off',
    type: "content",
    status: "PENDING",
    requester: MOCK_USERS[2],
    requestedAt: "2026-05-27T10:30:00Z",
    priority: "URGENT",
  },
  {
    id: "a2",
    title: '"Gravity" vertical edit (60s)',
    type: "content",
    status: "PENDING",
    requester: MOCK_USERS[2],
    requestedAt: "2026-05-27T09:00:00Z",
    priority: "HIGH",
  },
  {
    id: "a3",
    title: 'YouTube thumbnail — needs Key approval',
    type: "task",
    status: "REVISION_REQUESTED",
    requester: MOCK_USERS[5],
    requestedAt: "2026-05-26T16:00:00Z",
    priority: "HIGH",
  },
];

export const MOCK_ACTIVITY: ActivityItem[] = [
  {
    id: "ac1",
    user: MOCK_USERS[2],
    action: "uploaded",
    entityType: "asset",
    entityName: "Gravity_MV_final_cut_v3.mp4",
    timestamp: "2026-05-27T11:45:00Z",
  },
  {
    id: "ac2",
    user: MOCK_USERS[2],
    action: "submitted for approval",
    entityType: "content",
    entityName: '"Gravity" MV final cut — management sign-off',
    timestamp: "2026-05-27T10:30:00Z",
  },
  {
    id: "ac3",
    user: MOCK_USERS[5],
    action: "submitted for approval",
    entityType: "asset",
    entityName: '"Gravity" single announcement graphic',
    timestamp: "2026-05-27T09:20:00Z",
  },
  {
    id: "ac4",
    user: MOCK_USERS[3],
    action: "scheduled",
    entityType: "content",
    entityName: "Pre-save campaign launch — June 10",
    timestamp: "2026-05-27T08:00:00Z",
  },
  {
    id: "ac5",
    user: MOCK_USERS[4],
    action: "completed",
    entityType: "task",
    entityName: 'Press photos Set A — 25 selects delivered',
    timestamp: "2026-05-26T18:30:00Z",
  },
  {
    id: "ac6",
    user: MOCK_USERS[0],
    action: "approved",
    entityType: "asset",
    entityName: "Elijah — Album cover art (final)",
    timestamp: "2026-05-26T15:00:00Z",
  },
];

// ─── Analytics — real Spotify scale (1.27M monthly listeners, 342K followers) — Lil Tony Official ──

export const MOCK_ANALYTICS: AnalyticsSnapshot[] = [
  {
    platform: "instagram",
    followers: 89400,
    followersGrowth: 3.1,
    impressions: 620000,
    engagement: 31200,
    engagementRate: 5.0,
    shares: 8600,
    saves: 6100,
  },
  {
    platform: "tiktok",
    followers: 214000,
    followersGrowth: 7.4,
    impressions: 2100000,
    engagement: 118000,
    engagementRate: 5.6,
    shares: 44000,
    saves: 19000,
  },
  {
    platform: "youtube",
    followers: 41000,
    followersGrowth: 2.2,
    impressions: 310000,
    engagement: 18600,
    engagementRate: 6.0,
    shares: 3800,
    saves: 5200,
  },
  {
    platform: "spotify",
    // 342,354 followers, 1,273,747 monthly listeners
    followers: 342354,
    followersGrowth: 4.6,
    impressions: 1_273_747,
    engagement: 342354,
    engagementRate: 26.9, // saves/follows as % of listeners
    shares: 28000,
    saves: 94000,
  },
];

export const LIL_TONY_TOP_TRACKS = [
  { title: "3 AM", streams: "18.3M" },
  { title: "2 Sides To Every Story", streams: "15.8M" },
  { title: "Who's The Flyest", streams: "12.3M" },
  { title: "icon", streams: "8M" },
  { title: "Keyette", streams: "2.5M" },
];

export const MONTHLY_ENGAGEMENT_DATA = [
  { month: "Dec", instagram: 19000, tiktok: 64000,  youtube: 10000 },
  { month: "Jan", instagram: 22000, tiktok: 78000,  youtube: 11500 },
  { month: "Feb", instagram: 24000, tiktok: 91000,  youtube: 13000 },
  { month: "Mar", instagram: 27000, tiktok: 104000, youtube: 15000 },
  { month: "Apr", instagram: 29000, tiktok: 112000, youtube: 17200 },
  { month: "May", instagram: 31200, tiktok: 118000, youtube: 18600 },
];
