// Mock data for Caam1k — second artist workspace

export const CAAM1K_PHOTO =
  "https://i.scdn.co/image/ab6761610000e5ebe0b7e8617073ecad7baaee17";

export const CAAM1K_COVER =
  "https://i.scdn.co/image/ab67616d0000b27371c4e3aa789a84459742eb9b";

export const CAAM1K_RELEASES = [
  {
    id: "c-r1",
    title: "Eastside Evangelist",
    type: "Album",
    status: "ACTIVE" as const,
    releaseDate: "2026-04-10",
    label: "Son Of Yahweh Entertainment",
    coverImage: CAAM1K_COVER,
    tracklist: [
      "Eastside Story (Intro)",
      "Discernment",
      "False Prophets",
      "Everywhere I Go",
      "Free Game",
      "Don't Panic",
      "Heaven's Interlude",
      "Pray For Me",
      "Yahweh Flow",
      "Walkin' Saint",
      "7th Day",
      "Desert Eagle",
      "Last Supper",
      "For A Living",
      "Make It Home (Outro)",
    ],
  },
  {
    id: "c-r2",
    title: "God's Soldier",
    type: "Single",
    status: "POSTED" as const,
    releaseDate: "2025-11-08",
    label: "Son Of Yahweh Entertainment",
    coverImage: null,
    tracklist: ["God's Soldier"],
  },
  {
    id: "c-r3",
    title: "Cosmo & Wanda",
    type: "Album",
    status: "ACTIVE" as const,
    releaseDate: "2026-01-01",
    label: "Son Of Yahweh Entertainment",
    coverImage: "https://i.scdn.co/image/ab67616d000048518ada121453b0a009bfd8e31e",
    tracklist: ["Cosmo & Wanda"],
  },
];

export const CAAM1K_TOP_TRACKS = [
  { title: "Psalms 7", streams: "581K" },
  { title: "40 Days & 40 Nights", streams: "491K" },
  { title: "God's Soldier", streams: "465K" },
  { title: "Cosmo & Wanda", streams: "102K" },
  { title: "7th Day", streams: "80K" },
];

export const CAAM1K_CAMPAIGNS = [
  {
    id: "cc1",
    name: "Eastside Evangelist — Album Push",
    status: "ACTIVE" as const,
    phase: "ANALYTICS" as const,
    progress: 68,
    taskCount: 16,
    completedTasks: 11,
    startDate: "2026-03-14",
    endDate: "2026-06-30",
    platforms: ["instagram", "tiktok", "spotify", "youtube"],
  },
  {
    id: "cc2",
    name: "Everywhere I Go — Playlist Pitching",
    status: "ACTIVE" as const,
    phase: "POSTED" as const,
    progress: 85,
    taskCount: 8,
    completedTasks: 7,
    startDate: "2026-04-10",
    endDate: "2026-05-31",
    platforms: ["spotify"],
  },
  {
    id: "cc3",
    name: "Summer Single — Pre-Production",
    status: "PLANNING" as const,
    phase: "PLANNING" as const,
    progress: 12,
    taskCount: 10,
    completedTasks: 1,
    startDate: "2026-06-01",
    endDate: "2026-08-01",
    platforms: ["instagram", "tiktok", "spotify"],
  },
];

export const CAAM1K_TASKS = [
  {
    id: "ct1",
    title: "Edit 'Everywhere I Go' visualizer (YouTube cut)",
    status: "IN_PROGRESS" as const,
    priority: "HIGH" as const,
    assignee: "Darius",
    dueDate: "2026-05-28",
    campaignName: "Eastside Evangelist — Album Push",
  },
  {
    id: "ct2",
    title: "Design Eastside Evangelist merch mockups",
    status: "IN_REVIEW" as const,
    priority: "HIGH" as const,
    assignee: "Amara",
    dueDate: "2026-05-25",
    campaignName: "Eastside Evangelist — Album Push",
  },
  {
    id: "ct3",
    title: "Submit 'Everywhere I Go' to 5 Spotify editorial playlists",
    status: "DONE" as const,
    priority: "URGENT" as const,
    assignee: "Tati",
    dueDate: "2026-05-20",
    campaignName: "Everywhere I Go — Playlist Pitching",
  },
  {
    id: "ct4",
    title: "Don't Panic — TikTok lyric reel (30s cut)",
    status: "TODO" as const,
    priority: "MEDIUM" as const,
    assignee: "Darius",
    dueDate: "2026-06-02",
    campaignName: "Eastside Evangelist — Album Push",
  },
  {
    id: "ct5",
    title: "Write summer single treatment doc",
    status: "TODO" as const,
    priority: "MEDIUM" as const,
    assignee: "Tati",
    dueDate: "2026-06-10",
    campaignName: "Summer Single — Pre-Production",
  },
];

export const CAAM1K_APPROVALS = [
  {
    id: "ca1",
    title: "Eastside Evangelist merch mockups — v1",
    type: "content" as const,
    status: "PENDING" as const,
    requestedBy: "Amara",
    requestedAt: "2026-05-22T10:00:00Z",
    priority: "HIGH" as const,
  },
  {
    id: "ca2",
    title: "Everywhere I Go visualizer — final cut",
    type: "content" as const,
    status: "PENDING" as const,
    requestedBy: "Darius",
    requestedAt: "2026-05-21T14:30:00Z",
    priority: "HIGH" as const,
  },
  {
    id: "ca3",
    title: "Social copy — Everywhere I Go week 4 push",
    type: "task" as const,
    status: "REVISION_REQUESTED" as const,
    requestedBy: "Tati",
    requestedAt: "2026-05-20T09:00:00Z",
    priority: "MEDIUM" as const,
  },
];

export const CAAM1K_ANALYTICS = [
  {
    platform: "instagram",
    followers: 12400,
    followersGrowth: 4.3,
    impressions: 98000,
    engagement: 5200,
    engagementRate: 6.1,
    shares: 1800,
    saves: 2400,
  },
  {
    platform: "tiktok",
    followers: 8900,
    followersGrowth: 9.7,
    impressions: 210000,
    engagement: 14000,
    engagementRate: 7.8,
    shares: 4200,
    saves: 6100,
  },
  {
    platform: "spotify",
    followers: 7443,
    followersGrowth: 6.2,
    impressions: 75861,
    engagement: 7443,
    engagementRate: 9.8,
    shares: 900,
    saves: 8200,
  },
  {
    platform: "youtube",
    followers: 2100,
    followersGrowth: 3.1,
    impressions: 44000,
    engagement: 2600,
    engagementRate: 5.9,
    shares: 480,
    saves: 720,
  },
];

export const CAAM1K_MONTHLY_ENGAGEMENT = [
  { month: "Dec", instagram: 2800,  tiktok: 4200,  youtube: 800 },
  { month: "Jan", instagram: 3200,  tiktok: 5800,  youtube: 1000 },
  { month: "Feb", instagram: 3800,  tiktok: 7400,  youtube: 1400 },
  { month: "Mar", instagram: 4200,  tiktok: 9800,  youtube: 1800 },
  { month: "Apr", instagram: 4800,  tiktok: 12000, youtube: 2200 },
  { month: "May", instagram: 5200,  tiktok: 14000, youtube: 2600 },
];

export const CAAM1K_TEAM = [
  {
    id: "ct1",
    name: "Tatiyana",
    displayName: "Tati",
    email: "whoistati@thesighteproject.com",
    image: "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=96&h=96&fit=crop",
    role: "Creative Director",
    status: "ACTIVE" as const,
  },
  {
    id: "ct2",
    name: "Darius King",
    displayName: "Darius",
    email: "darius@liltonystudio.io",
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=96&h=96&fit=crop",
    role: "Editor",
    status: "BUSY" as const,
  },
  {
    id: "ct3",
    name: "Amara Osei",
    displayName: "Amara",
    email: "amara@liltonystudio.io",
    image: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=96&h=96&fit=crop",
    role: "Graphic Designer",
    status: "ACTIVE" as const,
  },
];

export const CAAM1K_ASSETS = [
  {
    id: "ca1",
    name: "EastsideEvangelist_cover_final.jpg",
    fileType: "image" as const,
    size: 4100000,
    thumbnailUrl: CAAM1K_COVER,
    tags: ["cover art", "Eastside Evangelist", "album"],
    uploader: "Amara",
    createdAt: "2026-03-10T10:00:00Z",
    folder: "Album Artwork",
  },
  {
    id: "ca2",
    name: "Caam1k_artist_photo_press.jpg",
    fileType: "image" as const,
    size: 5800000,
    thumbnailUrl: CAAM1K_PHOTO,
    tags: ["artist photo", "press kit", "promo"],
    uploader: "Darius",
    createdAt: "2026-03-05T14:00:00Z",
    folder: "Photos",
  },
  {
    id: "ca3",
    name: "Psalms7_visualizer_v1.mp4",
    fileType: "video" as const,
    size: 148000000,
    thumbnailUrl: null,
    tags: ["visualizer", "Psalms 7", "video"],
    uploader: "Darius",
    createdAt: "2026-05-18T11:00:00Z",
    folder: "Video Assets",
  },
  {
    id: "ca4",
    name: "EastsideEvangelist_master_final.wav",
    fileType: "audio" as const,
    size: 88000000,
    thumbnailUrl: null,
    tags: ["audio", "master", "album"],
    uploader: "Caam1k",
    createdAt: "2026-03-01T09:00:00Z",
    folder: "Audio",
  },
  {
    id: "ca5",
    name: "caam1k_press_kit_bio.docx",
    fileType: "document" as const,
    size: 48000,
    thumbnailUrl: null,
    tags: ["press kit", "bio", "Fort Worth"],
    uploader: "Tati",
    createdAt: "2026-04-15T16:00:00Z",
    folder: "Press",
  },
  {
    id: "ca6",
    name: "social_templates_caam1k_2026.psd",
    fileType: "design" as const,
    size: 18000000,
    thumbnailUrl: null,
    tags: ["template", "instagram", "design"],
    uploader: "Amara",
    createdAt: "2026-04-20T13:00:00Z",
    folder: "Templates",
  },
];

export const CAAM1K_CONTENT = [
  {
    id: "cc-ci1",
    title: "Everywhere I Go — Hook reel (Instagram/TikTok)",
    type: "REEL",
    phase: "POSTED",
    platforms: ["instagram", "tiktok"],
    scheduledAt: "2026-05-10T14:00:00Z",
  },
  {
    id: "cc-ci2",
    title: "Eastside Evangelist — Album trailer (YouTube)",
    type: "VIDEO",
    phase: "POSTED",
    platforms: ["youtube"],
    scheduledAt: "2026-03-12T16:00:00Z",
  },
  {
    id: "cc-ci3",
    title: "Don't Panic — Lyric video snippet",
    type: "REEL",
    phase: "EDITING",
    platforms: ["instagram", "tiktok"],
    scheduledAt: "2026-05-28T12:00:00Z",
  },
  {
    id: "cc-ci4",
    title: "Yahweh Flow — Testimony carousel",
    type: "CAROUSEL",
    phase: "REVIEW",
    platforms: ["instagram"],
    scheduledAt: "2026-06-05T18:00:00Z",
  },
  {
    id: "cc-ci5",
    title: "Fort Worth origin story — BTS doc clip",
    type: "VIDEO",
    phase: "PRODUCTION",
    platforms: ["youtube", "instagram"],
    scheduledAt: "2026-06-15T10:00:00Z",
  },
];

export const CAAM1K_CHANNELS = [
  { id: "ch1", name: "general",                  type: "text",         unread: 0, pinned: true },
  { id: "ch2", name: "announcements",             type: "announcement", unread: 1, pinned: true },
  { id: "ch3", name: "eastside-evangelist",       type: "text",         unread: 2, pinned: false },
  { id: "ch4", name: "everywhere-i-go-push",       type: "text",         unread: 0, pinned: false },
  { id: "ch5", name: "social-scheduling",         type: "text",         unread: 0, pinned: false },
];

export const CAAM1K_MESSAGES = [
  {
    id: "m1",
    author: { name: "Tatiyana", image: "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=96&h=96&fit=crop", status: "ACTIVE" as const },
    content: "Everywhere I Go visualizer is looking really strong. Darius, can you get the final cut into the approval queue today?",
    timestamp: "2026-05-21T10:28:00Z",
  },
  {
    id: "m2",
    author: { name: "Darius King", image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=96&h=96&fit=crop", status: "BUSY" as const },
    content: "Submitted! Also color graded the 30s TikTok cut — dropping it in assets now.",
    timestamp: "2026-05-21T10:45:00Z",
  },
  {
    id: "m3",
    author: { name: "Tatiyana", image: "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=96&h=96&fit=crop", status: "ACTIVE" as const },
    content: "Perfect. Amara — once the merch mockups are finalized, drop them in the queue too. Caam1k wants to review by Friday.",
    timestamp: "2026-05-21T11:00:00Z",
  },
  {
    id: "m4",
    author: { name: "Amara Osei", image: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=96&h=96&fit=crop", status: "ACTIVE" as const },
    content: "On it. Two colorways ready — doing final adjustments and will submit before EOD.",
    timestamp: "2026-05-21T11:20:00Z",
  },
];
